### ISSUE TITLE
Mechanizm obsługiwania algorytmów

### ISSUE THREAD

**Issue by Stanislaw-Golebiewski** [MikolajBalcerek/GlosBio#82]
<h4>Co dzieje się jeśli mamy gotowy algorytm i chcemy go 'wpiąć' do naszej apki?</h4>

Jakie ograniczenia nakładamy na osobę która chce przetestować swój program:

* trzeba umieścić wszystkie pliki w odpowiednim folderze na backendzie
* trzeba załączyć odpowiedni plik .json (możemy go nazwać np. _config.json_)
* pewnie wymagane będą dodatkowe biblioteki, trzeba zadbać o ich dostępność (np. pipenv w przypadku pythona)
* w _config.json_  trzeba w odpowiednim miejscu podać pełną komendę odpalającą nasz program oraz komendę do testowania uzyskanych modeli
* w _config.json_ podajemy miejsca w którym mają pojawić się pliki do trenowania i do testów

<h4>Jak to możemy zrealizować?</h4>
* odpalanie algorytmów na podstawie zawartości _config.json_ może być realizowane za pośrednictwem *AlgorytmManager*
* pliki pojawiające się w wyznaczonych folderach można zrealizować **symlinkami** do próbek w bazie, może być to realizowane przez *AlgorytmManager* przy pomocy *SampleManager*
* wiadomości/logi z treningów i testów dawane na standardowe wyjście można od razu wysyłać przez API na front.

**Comment by m1kra** [comment]
Planuję zrobić osobny plik z samą instrukcją dodawania algorytmów i napisać o nim / gdzie jest w README.

Co do 'config.json' - może możnaby posłużyć się make'iem, wtedy np. 'make install' odpalałoby komendy 'pip install' i  'pipenv install', a 'make run' uruchamiałoby aplikację?
